snakehubv1/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    
    path('', views.index,name='index'),
    path('home/', views.index,name='index'),
    path('signup/', views.registernl,name='registernl'),
    path('users/', views.newsletter_users,name='users'),
    path('about/', views.about,name='about'),

    
    
]

snakehubv1/snakehubv1/urls.py
from django.urls import path , include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    
    
]

snakehubv1/main/models.py
from django.db import models

# Create your models here.

#model for newsletter users

class NewsLetterUser(models.Model):
    name = models.CharField(max_length=50)
    phone_number= models.CharField(max_length=11)
    email = models.EmailField(unique=True)


    

snakehubv1/main/forms.py
from django import forms
from main.models import NewsLetterUser


class NewsLetterUserForm(forms.ModelForm):
    
    class Meta:
        model = NewsLetterUser
        fields = "__all__"

snakehubv1/main/views.py
from django.shortcuts import render
from main.forms import NewsLetterUserForm
from main.models import NewsLetterUser
# Create your views here.
def index(request):
    return render(request, 'main/index.html')



def registernl(request):
    form = NewsLetterUserForm()
    if request.method == 'POST':
        form = NewsLetterUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render(request, 'main/index.html')
        else:
            print('Error : Form invalid')
    return render(request, 'main/registernl.html',{'form':form})

         
        


    



def login_user(request):
    pass


def newsletter_users(request):
    users_list = NewsLetterUser.objects.order_by('name')
    return render(request, 'main/users.html',{'userdict':users_list})


def about(request):
    return render(request, 'main/about.html')


   

snakehubv1/templates/main/about.html
<!DOCTYPE html> {% extends 'main/base.html' %} {% load static %} {% block head_block %}
<title>About</title>
{% endblock %} {% block body_block %}

<h2>this is the version 1 of snake hub</h2>


<hr>
<p>these are the changes i like to apply in feuture versions :</p>
<p>1.in Newsletter-User page and other pages we need a space between contents and navbar</p>
<p>2.we need to sort the formgroup in signup page to look better, this isnt much beutiful</p>

<hr> {% endblock %}

snakehubv1/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lilita+One&display=swap');
    </style>
    <link rel="stylesheet" href="{% static 'css/main_nav.css' %}">
    {% block head_block  %}
    
    {% endblock  %}
    
    
</head>

<body>
    <!-- <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="#">
            <img src="https://www.pngfind.com/pngs/m/192-1923839_black-snake-png-transparent-png.png" width="30" height="30" class="d-inline-block align-top" alt=""> SnakeHub
        </a>

    </nav> -->

    <nav id="navid" class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="https://www.pngfind.com/pngs/m/192-1923839_black-snake-png-transparent-png.png" width="30" height="30" class="d-inline-block align-top" alt=""> SnakeHub
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:registernl' %}">SignUp-NewsLetter <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Login <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:users' %}">NewsLetter-Users <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:about' %}">About<span class="sr-only">(current)</span></a>
                </li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="type here.." aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    
    <div  class="container">
    {% block body_block  %}
    
    
    {% endblock  %}
</div>


    







</body>

</html>

snakehubv1/templates/main/index.html
<!DOCTYPE html>

{% extends 'main/base.html' %}
{% load static %}
{% block head_block  %}
<title>SnakeHub</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock  %}



{% block body_block  %}
    
<h1>Welcome to Home Page</h1>
<!-- bootstrap image gallery 1 -->
<div class="container-fluid">

    <div class="jumbotron">
      <h2 class="text-center">Snakes</h2>
      <p class="text-center">Snakes are elongated, limbless, carnivorous reptiles of the suborder Serpentes. Like all other squamates, snakes are ectothermic, amniote vertebrates covered in overlapping scales.</p>
    </div>
  
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2020/01/Snake-bush-viper-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 1</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2020/01/Snake-King-Brown-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 2</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2020/01/Snake-baby-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 3</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/12/Eastern-Mud-Snake-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 4</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/11/Best-Pet-Snakes-Garter-Snake-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 5</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/08/Animals-That-Lay-Eggs-snake-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 6</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/07/Flying-Snake-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 7</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/08/Fear-of-Animals_-Ophidiophobia-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 8</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/09/Are-snakes-mammals-puffing-snake-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 9</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2021/12/Texas-rat-snake-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 10</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2020/01/Snake-Pit-Vipet-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 11</figcaption>
        </figure>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-3">
        <figure>
          <img src="https://a-z-animals.com/media/2020/01/Snake-Blue-viper-768x401.jpg" class="img-thumbnail grayscale">
          <figcaption>Snake 12</figcaption>
        </figure>
      </div>
    </div>
  </div>
    
    {% endblock  %}

snakehubv1/templates/main/registernl.html
<!DOCTYPE html> {% extends 'main/base.html' %} {% block head_block %}
<title>Register</title>

{% endblock %} {% block body_block %}


<h1>register </h1>
<h4>complete the info and hit submit to join the newsletter and get notfied by updates!</h4>
<form method="POST">
    {{form.as_p}} {% csrf_token %}
    <input type="submit" class='btn btn-dark'>
</form>
{% endblock %}

snakehubv1/templates/main/users.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
{% block head_block %}
<title>Newletter Usere</title>

{% endblock %}

{% block body_block  %}
    
<h3>list of interested people:  </h3>

{% for person in userdict  %}
<ul>
    <li>{{person.name}}</li>
    <li>{{person.phone_number}}</li>
    <li>{{person.email}}</li>
</ul>
<hr>

{% endfor %}



    
    {% endblock  %}